// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoEdificios.Data.Models;

#nullable disable

namespace ProyectoEdificios.Migrations
{
    [DbContext(typeof(ProyectoEdificiosDbContext))]
    [Migration("20260120195302_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoEdificios.Data.Models.Apartamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Adeudado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodUnidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DescargadaDGII")
                        .HasColumnType("bit");

                    b.Property<string>("Edificio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EnInspeccion")
                        .HasColumnType("bit");

                    b.Property<bool?>("Entregada")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCompletaInicial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregaInspeccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFormaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaGobierno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioVaciados")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInspeccion1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInspeccion2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLegal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaMicelaneos")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gobierno")
                        .HasColumnType("bit");

                    b.Property<bool?>("IniciadoVaciados")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Inicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InicialDolar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Inspeccion1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Inspeccion2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Legal")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Metraje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Micelaneos")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResponsableGobierno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableMicelaneos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Saldo")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Titulo")
                        .HasColumnType("bit");

                    b.Property<string>("Unidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apartamento", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Data.Models.Edificio", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Color")
                        .HasColumnType("int")
                        .HasColumnName("color");

                    b.Property<int?>("Columns")
                        .HasColumnType("int")
                        .HasColumnName("columns");

                    b.Property<int?>("CubeScale")
                        .HasColumnType("int")
                        .HasColumnName("cubeScale");

                    b.Property<int?>("FootprintScale")
                        .HasColumnType("int")
                        .HasColumnName("footprintScale");

                    b.Property<string>("ImagenPlano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("projectID");

                    b.Property<int?>("Rotation")
                        .HasColumnType("int")
                        .HasColumnName("rotation");

                    b.Property<int?>("Rowspercolumn")
                        .HasColumnType("int")
                        .HasColumnName("rowspercolumn");

                    b.Property<int?>("TotalUnits")
                        .HasColumnType("int")
                        .HasColumnName("totalUnits");

                    b.Property<string>("UnitKeys")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unitKeys");

                    b.Property<string>("Units")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("units");

                    b.Property<double?>("X")
                        .HasColumnType("float")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("float")
                        .HasColumnName("y");

                    b.Property<double?>("Z")
                        .HasColumnType("float")
                        .HasColumnName("z");

                    b.HasKey("Name")
                        .HasName("PK__edificio__72E12F1AA1E2E413");

                    b.HasIndex("ProjectId");

                    b.ToTable("edificios", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Data.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provincia");

                    b.HasKey("Id")
                        .HasName("PK__project__3213E83F77DE65FA");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("clave");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Salt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("salt");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83FE77DD8CD");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164465182F2")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Data.Models.Edificio", b =>
                {
                    b.HasOne("ProyectoEdificios.Data.Models.Project", "Project")
                        .WithMany("Edificios")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Edificios_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProyectoEdificios.Data.Models.Project", b =>
                {
                    b.Navigation("Edificios");
                });
#pragma warning restore 612, 618
        }
    }
}
