// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoEdificios.Data.Contexts;

#nullable disable

namespace ProyectoEdificios.Migrations
{
    [DbContext(typeof(ProyectoEdificiosDbContext))]
    [Migration("20260320081633_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.LayoutBuilding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<int>("ProjectLayoutId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectLayoutId");

                    b.HasIndex("ProjectLayoutId", "Name");

                    b.ToTable("LayoutBuildings", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.LayoutUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ExternalUnitCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LayoutBuildingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUnitCode");

                    b.HasIndex("LayoutBuildingId");

                    b.HasIndex("LayoutBuildingId", "Name");

                    b.ToTable("LayoutUnits", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Province", "Municipality");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.ProjectLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GridSize")
                        .HasColumnType("int");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectLayouts", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("viewer");

                    b.Property<string>("Salt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.LayoutBuilding", b =>
                {
                    b.HasOne("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.ProjectLayout", "ProjectLayout")
                        .WithMany("Buildings")
                        .HasForeignKey("ProjectLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectLayout");
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.LayoutUnit", b =>
                {
                    b.HasOne("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.LayoutBuilding", "Building")
                        .WithMany("Units")
                        .HasForeignKey("LayoutBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.ProjectLayout", b =>
                {
                    b.HasOne("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.Project", "Project")
                        .WithOne("Layout")
                        .HasForeignKey("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.ProjectLayout", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.LayoutBuilding", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.Project", b =>
                {
                    b.Navigation("Layout");
                });

            modelBuilder.Entity("ProyectoEdificios.Models.Entities.ProjectLayoutEntities.ProjectLayout", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
